### ISSUE TITLE
Add Assertoor GitHub action

### ISSUE THREAD

**Issue by eth2353** [serenita-org/vero#104]
Add a GitHub action that runs a Kurtosis devnet with Vero as the only validator client. Use assertoor to check the network finalizes - this means Vero is successfully attesting and producing blocks.

The config could be as simple as this:

```
participants:
  - el_type: nethermind
    cl_type: lodestar
    use_separate_vc: true
    vc_type: vero
    use_remote_signer: true

[... Assertoor config ...]
```

This would not completely replace manual testing on local devnets but would serve as a good sanity check / integration test before releasing a new Vero version.

Depending on the action runtime, we may only want to run it manually before a release. It would also be good if we could manually trigger it against a specific PR.
